### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by mathieudutour** [prodo-dev/prodo#132]
@Onurbon asked me to have a look so here are a couple of thoughts:
- add a `## Installation` that I can copy paste in the readme 😄 
- I've been using a lot of hooks lately and I really like the mental model behind it. I'm wondering if it could be ported to `prodo`:
```js
import * as React from "react";
import { useState, useAction } from "@prodo/react";
import { State } from "../types";

const App = () => {
  // `setCount` would be `dispatch(model.action(state => x => { fnPassedToUseState(state) = x })) behind the scene
  const [count, setCount] = useState((state: State) => state.count)
  
  // in case `useState` isn't enough
  const action = useAction((state: State) => {
    // do whatever
  })
  return (
    <div>
      <button onClick={() => setCount(count - 1)}>-</button>
      <h1>{count}</h1>
      <button onClick={() => setCount(count + 1)}>+</button>
    </div>
  );
}

export default App;
```

You will note a few things:
- import `@prodo/react` instead of a relative path. That means that you can potentially share components using global states as long as they use prodo (could be useful to create a design system, etc.).
- no need to `watch`/`dispatch`, the `useState` automatically returns what's needed (it should be possible as long as the component is nested inside a `Provider`, right?)

**Comment by mathieudutour** [comment]
Trying it with Gatsby and it works quite nicely.

You need 2 files:
- `gatsby-browser.js`:
	```js
	import React from 'react'
	import { model } from './src/store'
	
	const { Provider } = model.createStore({
	  initState: {
	    loadingUser: false,
	  },
	  initLocal: {
	    user: null,
	  },
	})
	
	export const wrapRootElement = ({ element }) => {
	  return <Provider>{element}</Provider>
	}
	```
- `gatsby-ssr.js`:
	```js
	import React from 'react'
	import { model } from './src/store'
	
	const { Provider } = model.createStore({
	  initState: {
	    loadingUser: false,
	  },
	  // need `localFixture` because `localStorage` doesn't exist on server-side
	  localFixture: {
	    user: null,
	  },
	})
	
	export const wrapRootElement = ({ element }) => {
	  return <Provider>{element}</Provider>
	}
	```
And then you can use your store on any page.

**Comment by mathieudutour** [comment]
You really need to write somewhere that the file where the model is **needs** to be called `model`, I spent so much time trying to understand why everything was undefined

**Comment by coffee-cup** [comment]
Thanks for the great feedback @mathieudutour! Very good point about mentioning that the model file needs to be called `model`.

> Maybe instead of being undefined until the babel plugin change them, watch and dispatch could be functions that throws with a nice error message

We have noted that using `state`, `watch`, and `dispatch` incorrectly could result in a terrible error message (https://github.com/prodo-ai/prodo/issues/34). We have an experiemental ESLint plugin that will error when using `state` outside of an action or component, but throwing a nice error message when using `watch` or `dispatch` would be really helpful.

> I just now realised that it's all based on Proxy. As far as I know, babel can't polyfill Proxies.

This definitly isn't great. We are looking into how we can polyfill proxies for browsers that do not support it. [This looks promising](https://github.com/GoogleChrome/proxy-polyfill), yet still does not polyfill all traps we use.

**Comment by mathieudutour** [comment]
> We have an experiemental ESLint plugin that will error when using state outside of an action or component

I don't think that's enough: if your model is not in `model.ts`, then it will fail even if used in an action.

So while an eslint plugin would be nice, I think a nice runtime error would be better. 
Thinking more about it, `watch` and `dispatch` aren't enough because `watch(state.foo)` will fail with `can't read foo of undefined` because calling the function. So probably need a catch-all proxy that throws all the time.

**Comment by coffee-cup** [comment]
Yes that's a good point.
