### ISSUE TITLE
Yarn Cache Issue

### ISSUE THREAD

**Issue by andrejak** [prodo-dev/prodo#180]
When trying to create project through:
`yarn create prodo-app my-app --typescript`

Sometimes people get the error:
`error Incorrect integrity when fetching from the cache`

**Workaround:**
Run `yarn cache clean` or use npx.

**Comment by coffee-cup** [comment]
This isn't just an issue with Prodo. Not sure if we can do anything about it, https://stackoverflow.com/questions/58172688/incorrect-integrity-when-fetching-from-the-cache

**Comment by andrejak** [comment]
I'll take off the bug label, but I thought it was said this morning we wanted problems that users were running into to be easily findable in Issues? Kai said that was the first thing he'd check.

**Comment by coffee-cup** [comment]
I think that was more for issues related to the framework/library itself. If a user encountered this error, they would quickly find its an issue with Yarn rather than Prodo. @kwohlfahrt can comment on this, but I'm not sure we should be documenting issues unrelated to Prodo here.

**Comment by andrejak** [comment]
sure. But it seems that 2/3 external people who have tried making an app have hit it and asked for our help about it, so it would be helpful to document it somewhere.

**Comment by andrejak** [comment]
Ok, I'll close this. Would still be good to know if there's a reason so many of our users are hitting yarn cache issues, but I guess that's low priority for now.
