### ISSUE TITLE
action events should have unique ids

### ISSUE THREAD

**Issue by Onurbon** [prodo-dev/prodo#42]
The generated ids for the actions triggered from a react component are not unique yet. See below two different actions triggered from the same component:

![image](https://user-images.githubusercontent.com/3934784/64691808-821d1f00-d48b-11e9-8be4-903d03704ba3.png)

**Comment by andrejak** [comment]
Assuming this is done since id is now in the format "Component.number/event.number", should this be closed?

**Comment by coffee-cup** [comment]
I'm pretty sure this is closed now
